#!/usr/bin/env bash
# Display list of currently running directories
# Must show all processes, for all users, including those which might not have a TTY
# Display in a user-oriented format

ps -a -x -u -f
