#!/usr/bin/env bash
# displays lines containing the bash word, thus allowing you to easily get the PID of your Bash
# You cannot use pgrep
# The third line of your script must be # shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
